---
steps:
  - command: "echo 'Hello, world!'"
    env:
      JSON: {"key": "this shouldn't work"}
  - command: "echo 'Hello, world!'"
    label: ":wave: Hello, world!"
  - command: source ./script.sh
