---
steps:
  - command: echo $$COLOUR $$SHAPE
    env:
      "COLOUR": "{{matrix.color}}"
      "SHAPE": "{{matrix.shape}}"
    matrix:
      setup:
        color:
          - red
          - green
          - blue
        shape:
          - circle
          - square
          - triangle
