---
steps:
  - command: echo "hello"
  - group: ":hammer_and_wrench: Binary builds"
    steps:
    - name: ":{{matrix.os}}: Build {{matrix.os}} {{matrix.arch}} binary"
      command: ".buildkite/steps/build-binary.sh {{matrix.os}} {{matrix.arch}}"
      key: build-binary
      depends_on:
        # don't wait for slower windows tests
        - test-linux-amd64
        - test-linux-arm64
      artifact_paths: "pkg/*"
      plugins:
        docker-compose#v4.14.0:
          config: .buildkite/docker-compose.yml
          cli-version: 2
          run: agent
      matrix:
        setup:
          os:
            - darwin
            - freebsd
            - linux
            - openbsd
            - windows
          arch:
            - "386"
            - amd64
            - arm64
        adjustments:
          - with: { os: darwin, arch: "386" }
            skip: "macOS no longer supports x86 binaries"

          - with: { os: dragonflybsd, arch: amd64 }

          - with: { os: freebsd, arch: arm64 }
            skip: "arm64 FreeBSD is not currently supported"

          - with: { os: linux, arch: arm }
          - with: { os: linux, arch: armhf }
          - with: { os: linux, arch: ppc64 }
          - with: { os: linux, arch: ppc64le }
          - with: { os: linux, arch: mips64le }
          - with: { os: linux, arch: s390x }

          - with: { os: netbsd, arch: amd64 }

          - with: { os: openbsd, arch: arm64 }
            skip: "arm64 OpenBSD is not currently supported"
