---
steps:
  - command: "echo 'Hello, world!'"
    label: ":wave: Hello, world!"
  - command: "ruby .buildkite/steps/generate_steps.rb | buildkite-agent pipeline upload"
    label: ":pipeline: :ruby: Generate steps"
