---
env:
  AURORA_BAZEL_CONFIG_CI: "true"
  QUEUE_CAPABILITIES: {"custom": true, "hooks_image": "experiment", "env": "staging"}

steps:
  - command: "echo 'Hello, world!'"
  - command: "echo 'Hello, world!'"
    label: ":wave: Hello, world!"
  - command: source ./script.sh
