#!/usr/bin/env bash

set -ex

echo "redacted vars is: $BUILDKITE_REDACTED_VARS"

SECRET=`buildkite-agent secret get cool_secret`

echo "The secret is $SECRET"

echo "secret from pipeline env is $NOT_A_TOKEN"
